compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[kv_namespaces]]
binding = "KV"
id = "kv_default"

[[kv_namespaces]]
binding = "CACHE"
id = "cache_default"

[[d1_databases]]
binding = "DB"
database_name = "default"
database_id = "default"
migrations_dir = "server/database/migrations"
