-- Generated by Drizzle (DO NOT EDIT THIS PART)
-- Adding sex column to publishers table
-- Manual addition: Data migration for existing publishers
-- All existing publishers in seed data are male, so we set default to 'male'

-- Step 1: Add column as nullable first (to allow existing rows)
ALTER TABLE `publishers` ADD `sex` text;

-- Step 2: Update all existing records with 'male' (all seed publishers are male)
UPDATE `publishers` SET `sex` = 'male' WHERE `sex` IS NULL;

-- Step 3: Make column NOT NULL after all existing data is updated
-- Note: SQLite doesn't support ALTER COLUMN, so we need to recreate the table
-- For development/seeding purposes, the column is now populated and will be NOT NULL in schema