export const AUDIT_EVENTS = {
  TALK_STATUS_CHANGED: "talk_status_changed",
  TALK_EDITED: "talk_edited",
  TALK_CREATED: "talk_created",
  TALK_DELETED: "talk_deleted",
  SPEAKER_CREATED: "speaker_created",
  SPEAKER_EDITED: "speaker_edited",
  SPEAKER_ARCHIVED: "speaker_archived",
  SPEAKER_RESTORED: "speaker_restored",
  SCHEDULE_CREATED: "schedule_created",
  SCHEDULE_UPDATED: "schedule_updated",
  SCHEDULE_DELETED: "schedule_deleted",
  SCHEDULE_VALIDATION_OVERRIDDEN: "schedule_validation_overridden",
  PERMISSION_DENIED: "permission_denied",
  UNAUTHORIZED_ACCESS: "unauthorized_access",
} as const
