export const AUDIT_EVENTS = {
  TALK_STATUS_CHANGED: "talk_status_changed",
  TALK_EDITED: "talk_edited",
  TALK_CREATED: "talk_created",
  TALK_DELETED: "talk_deleted",
  SPEAKER_CREATED: "speaker_created",
  SPEAKER_EDITED: "speaker_edited",
  SPEAKER_ARCHIVED: "speaker_archived",
  SPEAKER_RESTORED: "speaker_restored",
  SPEAKER_UPDATED_FROM_IMPORT: "speaker_updated_from_import",
  SPEAKER_CONGREGATION_TRANSFERRED: "speaker_congregation_transferred",
  SCHEDULE_CREATED: "schedule_created",
  SCHEDULE_UPDATED: "schedule_updated",
  SCHEDULE_DELETED: "schedule_deleted",
  SCHEDULE_VALIDATION_OVERRIDDEN: "schedule_validation_overridden",
  PUBLISHER_CREATED: "publisher_created",
  PUBLISHER_UPDATED: "publisher_updated",
  PUBLISHER_USER_LINKED: "publisher_user_linked",
  PUBLISHER_USER_UNLINKED: "publisher_user_unlinked",
  WEEKEND_MEETING_PLANNED: "weekend_meeting_planned",
  WEEKEND_MEETING_UPDATED: "weekend_meeting_updated",
  MEETING_EXCEPTION_CREATED: "meeting_exception_created",
  MEETING_EXCEPTION_UPDATED: "meeting_exception_updated",
  MEETING_EXCEPTION_DELETED: "meeting_exception_deleted",
  PERMISSION_DENIED: "permission_denied",
  UNAUTHORIZED_ACCESS: "unauthorized_access",
} as const
